### ISSUE TITLE
describe event storming process

### ISSUE THREAD

**Issue by matthaeusheer** [iptch-public/2022-fall-architectural-katas#11]
- [x] add overview to README, probably with final sticker image
- [x] add detailed subpage
- [x] detail page: describe the process briefly and link to resources
- [x] detail page: describe our common terminology
- [x] detail page: show story, where we started and where we went
- [x] detail page: describe capabilites we came up with

**Comment by matthaeusheer** [comment]
do we really need a sub-page here or is the current state of description in the README enough @NicolasMesot @riedelmax

**Comment by riedelmax** [comment]
IMO its detailed enough but we should take it off the main page and to a subpage to reduce bloat.

We should also discuss if we want to take the big diagrams for capabilities off the main page and only show them in the detailed subpage or maybe small versions with links to the subpage (kinda like in https://github.com/miyagis-forests/farmacy-food-kata)
